name: All Green

on:
  workflow_call:

jobs:
  all-green:
    name: All Green
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: All Green
        uses: getdevopspro/github-actions/all-green@v6.6.0
